name: Documentation
on:
  pull_request:
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
permissions:
  contents: read

jobs:
  test-documentation:
    runs-on: ubuntu-20.04
    name: Test Generating Docs
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 16

      - run: npm install
      - run: npm run docs:clean
      - run: npm run docs:generate
